name: Daily crawler (keywords)

on:
  schedule:
    - cron: "5 6 * * *"   # هر روز ساعت 06:05 UTC (08:35 به وقت ایران، 08:05 NL؟ حسب نیاز تغییر بده)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run crawler
        run: |
          python scripts/crawler.py

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/crawler.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: crawler results [skip ci]"
            git push origin main
          fi
